spring:
  liquibase:
    change-log: classpath:db/changelog-master.xml
    drop-first: true
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:

  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
      username: sa


