spring:
  liquibase:
    change-log: classpath:db/changelog/001-init-changelog.xml
    drop-first: true
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
  r2dbc:
    url: r2dbc:h2:file:///~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

